// Danish translations: English text → Danish. Numbers in keys are written as {0}, {1}, …
// Leading/trailing emoji and symbols are handled by the engine, so "🎯 Title ✓" only needs "Title".
(function (g) {
  const DG = g.DG;
  const D = {
    // ---------- qualities ----------
    'Quality': 'Kvalitet', 'Workwear': 'Arbejdstøj', 'Creativity': 'Kreativitet', 'Exclusivity': 'Eksklusivitet', 'Elegance': 'Elegance', 'Comfort': 'Komfort',
    'beautifully made': 'smukt syet', 'tough enough for a working day': 'robust nok til en arbejdsdag', 'creative and original': 'kreativ og original',
    'exclusive, truly one of a kind': 'eksklusiv og helt unik', 'elegant': 'elegant', 'comfortable': 'behagelig',

    // ---------- fabrics ----------
    'Polyester': 'Polyester', 'Cotton': 'Bomuld', 'Jersey': 'Jersey', 'Linen': 'Hør', 'Denim': 'Denim', 'Canvas': 'Kanvas', 'Chiffon': 'Chiffon',
    'Satin': 'Satin', 'Wool': 'Uld', 'Lace': 'Blonde', 'Tweed': 'Tweed', 'Velvet': 'Fløjl', 'Silk': 'Silke', 'Organza': 'Organza', 'Brocade': 'Brokade', 'Cashmere': 'Kashmir',
    'Cheap and cheerful. Nobody brags about it.': 'Billigt og muntert. Ingen praler med det.',
    'The honest all-rounder.': 'Den ærlige allrounder.',
    'Stretchy, soft and forgiving.': 'Strækbar, blød og tilgivende.',
    'Breezy summer classic. Wrinkles with pride.': 'Luftig sommerklassiker. Krøller med stolthed.',
    'Built to survive anything.': 'Bygget til at overleve alt.',
    'Basically a very durable tent.': 'Nærmest et meget slidstærkt telt.',
    'Light and floaty. Fears staplers.': 'Let og svævende. Frygter hæftemaskiner.',
    'Glossy evening shine.': 'Blank aftenglans.',
    'Warm, structured and long-lasting.': 'Varm, struktureret og holdbar.',
    'Delicate floral openwork.': 'Fint gennembrudt blomstermønster.',
    'Heritage texture with attitude.': 'Klassisk struktur med attitude.',
    'Deep, plush and dramatic.': 'Dyb, blød og dramatisk.',
    'The real deal. Handle with love.': 'Den ægte vare. Håndteres med kærlighed.',
    'Crisp, sheer and sculptural.': 'Sprød, gennemsigtig og skulpturel.',
    'Woven gold motifs. Royalty approved.': 'Indvævede guldmotiver. Godkendt af kongehuset.',
    'Unreasonably soft. Unreasonably priced.': 'Urimeligt blød. Urimeligt dyr.',

    // ---------- colours ----------
    'White': 'Hvid', 'Ivory': 'Elfenben', 'Blush': 'Rosa', 'Rose': 'Rosenrød', 'Red': 'Rød', 'Coral': 'Koral', 'Mustard': 'Sennepsgul', 'Sage': 'Salvie',
    'Emerald': 'Smaragd', 'Sky blue': 'Himmelblå', 'Indigo': 'Indigo', 'Navy': 'Marineblå', 'Lavender': 'Lavendel', 'Plum': 'Blomme', 'Brown': 'Brun', 'Black': 'Sort',

    // ---------- dress parts ----------
    'A-line': 'A-linje', 'Sheath': 'Etui', 'Wrap': 'Slå-om', 'Shirt dress': 'Skjortekjole', 'Empire': 'Empire', 'Pinafore': 'Forklædekjole', 'Mermaid': 'Havfrue', 'Ball gown': 'Balkjole',
    'Mini': 'Mini', 'Knee': 'Knælang', 'Midi': 'Midi', 'Maxi': 'Maxi',
    'Round': 'Rund', 'V-neck': 'V-hals', 'Square': 'Firkantet', 'Collar': 'Krave', 'Sweetheart': 'Hjerteformet', 'Off-shoulder': 'Off-shoulder', 'Halter': 'Halterneck',
    'Sleeveless': 'Ærmeløs', 'Cap': 'Kappeærme', 'Short': 'Kort', 'Long': 'Lang', 'Puff': 'Pufærme', 'Bell': 'Klokkeærme',
    'None': 'Ingen', 'Zipper': 'Lynlås', 'Plastic buttons': 'Plastikknapper', 'Wooden buttons': 'Træknapper', 'Brass buttons': 'Messingknapper', 'Pearl buttons': 'Perlemorsknapper', 'Gold buttons': 'Guldknapper',
    'Pockets': 'Lommer', 'Reinforced seams': 'Forstærkede sømme', 'Ruffles': 'Flæser', 'Belt': 'Bælte', 'Bow': 'Sløjfe', 'Lace trim': 'Blondekant', 'Sequins': 'Pailletter',
    'Embroidery': 'Broderi', 'Crystal beading': 'Krystalbroderi', 'Ribbon': 'Bånd', 'Embroidery thread': 'Broderigarn', 'Crystal beads': 'Krystalperler',

    // ---------- upgrades ----------
    'Sewing machine': 'Symaskine', 'Wider stitch zone, slower needle and +{0} quality per level.': 'Bredere stingzone, langsommere nål og +{0} kvalitet pr. niveau.',
    'Shop window': 'Butiksvindue', 'Room for more customers each day, and they bring bigger budgets.': 'Plads til flere kunder hver dag, og de har større budgetter med.',
    'Supplier network': 'Leverandørnetværk',
    'Level {0}: wool, lace, tweed, velvet, silk, pearl buttons. Level {1}: organza, brocade, cashmere, gold buttons.': 'Niveau {0}: uld, blonde, tweed, fløjl, silke og perlemorsknapper. Niveau {1}: organza, brokade, kashmir og guldknapper.',
    'Embroidery machine': 'Broderimaskine', 'Level {0} unlocks embroidery. Level {1} unlocks crystal beading.': 'Niveau {0} låser op for broderi. Niveau {1} låser op for krystalbroderi.',
    'Market haggling': 'Prutning på markedet', '{0}% off everything at the market, per level.': '{0}% rabat på alt på markedet pr. niveau.',
    'Accountant (revisor)': 'Revisor',
    'Lower SKAT. Level {0}: finds {1} kr more deductions every day. Level {2}: virksomhedsordningen cuts the top rate from {3}% to {4}% and finds {5} kr of deductions a day.': 'Lavere skat. Niveau {0}: finder {1} kr flere fradrag hver dag. Niveau {2}: virksomhedsordningen sænker topskatten fra {3}% til {4}% og finder {5} kr fradrag om dagen.',
    'Cozy fitting room': 'Hyggeligt prøverum', '+{0} satisfaction per level, and happy customers tip more.': '+{0} tilfredshed pr. niveau, og glade kunder giver flere drikkepenge.',
    'Pottery studio': 'Keramikværksted',
    "Level {0}: a potter's wheel and a small kiln for {1} pots. Level {2}: an electric kiln for {3} pots, half as many cracks, and {4} more shelf spaces.": 'Niveau {0}: en drejeskive og en lille brændeovn til {1} potter. Niveau {2}: en elektrisk ovn til {3} potter, halvt så mange revner og {4} pladser mere på hylden.',
    'Upstairs floor': '1. sal', 'Opens the first floor: +{0} customer per day, room for {1} more, and +{2} rack hangers.': 'Åbner 1. sal: +{0} kunde om dagen, plads til {1} mere og +{2} bøjler på stativet.',

    // ---------- seasons ----------
    'Spring': 'Forår', 'Summer': 'Sommer', 'Autumn': 'Efterår', 'Winter': 'Vinter',
    'Spring has arrived! Wedding season is starting.': 'Foråret er kommet! Bryllupssæsonen begynder.',
    'Summer! Everyone wants something light and breezy.': 'Sommer! Alle vil have noget let og luftigt.',
    'Autumn leaves are falling. Back to work and back to the office.': 'Bladene falder. Tilbage til arbejdet og kontoret.',
    'Winter is here. Time for warm dresses and glittering galas.': 'Vinteren er her. Tid til varme kjoler og glitrende gallaer.',

    // ---------- pottery ----------
    'Terracotta': 'Terrakotta', 'Stoneware': 'Stentøj', 'Porcelain': 'Porcelæn',
    'Warm, rustic and forgiving.': 'Varm, rustik og tilgivende.', 'Sturdy everyday clay.': 'Robust hverdagsler.',
    'Translucent and precious. Needs supplier level {0}.': 'Gennemskinnelig og kostbar. Kræver leverandørniveau {0}.',
    'Cup': 'Kop', 'Bowl': 'Skål', 'Plate': 'Tallerken', 'Vase': 'Vase', 'Teapot': 'Tekande', 'Mug': 'Krus', 'Planter': 'Urtepotte', 'Jug': 'Kande', 'Amphora': 'Amfora',
    'Unglazed': 'Uglaseret', 'Speckled cream': 'Prikket creme', 'Celadon': 'Seladon', 'Cobalt blue': 'Koboltblå', 'Copper red': 'Kobberrød', 'Gold lustre': 'Guldglans',
    'Plain': 'Glat', 'Carved lines': 'Indridsede linjer', 'Painted flowers': 'Malede blomster', 'Gold rim': 'Guldkant', 'Hand-painted': 'Håndmalet', 'Gold leaf': 'Bladguld',

    // ---------- home ----------
    'Crayons and paper': 'Farvekridt og papir', 'Elizabeth draws dresses "just like Mama".': 'Elizabeth tegner kjoler "ligesom mor".',
    'Teddy bear': 'Bamse', 'Named Bamse, obviously.': 'Han hedder selvfølgelig Bamse.',
    'Wooden train': 'Togbane i træ', 'Choo-choo all around the living room.': 'Tøf-tøf rundt i hele stuen.',
    'Puppet theatre': 'Dukketeater', 'Starring Dexter, against his will.': 'Med Dexter i hovedrollen, mod hans vilje.',
    'Tricycle': 'Trehjulet cykel', 'Fast. Too fast, says Adam.': 'Hurtig. For hurtig, siger Adam.',
    'Dollhouse': 'Dukkehus', 'With a tiny atelier on the ground floor.': 'Med et bitte lille atelier i stueetagen.',
    'Feather wand': 'Fjerpind', 'Dexter pretends not to care. He cares.': 'Dexter lader som om han er ligeglad. Det er han ikke.',
    'Scratching post': 'Kradsetræ', 'Saves the sofa. Mostly.': 'Redder sofaen. For det meste.',
    'Cat bed': 'Kattekurv', 'He still sleeps on the fabric pile.': 'Han sover stadig på stofbunken.',
    'Cat tower': 'Kattetårn', 'King Dexter surveys his kingdom.': 'Kong Dexter skuer ud over sit rige.',
    'Cat food ({0} days)': 'Kattemad ({0} dage)',
    'Play with Elizabeth': 'Leg med Elizabeth', 'Pet Dexter': 'Ae Dexter', 'Dinner at home': 'Aftensmad derhjemme', 'Welcome back': 'Velkommen tilbage', 'Stickers': 'Klistermærker', '{0} of {1}': '{0} af {1}', '{0} new stickers in the album.': '{0} nye klistermærker i albummet.',
    'The first dress': 'Den første kjole', 'Fifty dresses': 'Halvtreds kjoler', 'Two hundred dresses': 'To hundrede kjoler', 'A five-star dress': 'En femstjernet kjole',
    'The first bride': 'Den første brud', 'A pot sold': 'En solgt krukke', 'A teapot': 'En tekande', 'A five-star shop': 'En femstjernet butik',
    'A home of their own': 'Et hjem for sig selv', 'The Strandvej villa': 'Villaen på Strandvejen', 'The first tulip': 'Den første tulipan', "Dexter's first trick": 'Dexters første trick',
    'A doll dress': 'En dukkekjole', 'A full collection': 'En fuld samling', 'Ten lookbook pages': 'Ti sider i lookbogen', 'A story told to the end': 'En historie fortalt til ende', 'A year in the shop': 'Et år i butikken', 'Wardrobe': 'Garderobe', 'Garden': 'Have', 'The garden': 'Haven', 'The balcony': 'Altanen',
    'Autumn is tulip time: plant bulbs now and they bloom in spring.': 'Efterår er tulipantid: Læg løgene nu, så blomstrer de til foråret.',
    'The garden sleeps under the snow. The bulbs are dreaming of spring.': 'Haven sover under sneen. Løgene drømmer om foråret.',
    'Tap a tulip to pick a bouquet for the dinner table.': 'Tryk på en tulipan for at plukke en buket til middagsbordet.',
    'Bulbs planted now rest until next spring.': 'Løg, der lægges nu, hviler til næste forår.',
    'Pick a colour, then tap an empty bed. Bulbs cost {0} kr': 'Vælg en farve, og tryk på et tomt bed. Løg koster {0} kr',
    'The ground is frozen. Plant again when spring comes.': 'Jorden er frossen. Læg løg igen, når foråret kommer.',
    'Not enough money for a bulb.': 'Ikke penge nok til et løg.', 'A bouquet for the dinner table.': 'En buket til middagsbordet.',
    "Elizabeth's sewing corner": 'Elizabeths syhjørne', 'Sew it!': 'Sy den!',
    'Elizabeth hung her new doll dress on the line.': 'Elizabeth hængte sin nye dukkekjole op på snoren.',
    'Elizabeth has sewn enough for today.': 'Elizabeth har syet nok for i dag.',
    'Her own sewing corner': 'Sit eget syhjørne', "A little table and a toy sewing machine, just like Mama's. One doll dress a day.": 'Et lille bord og en legetøjssymaskine, ligesom mors. Én dukkekjole om dagen.',
    'Teach Dexter a trick': 'Lær Dexter et trick', 'Training done for today': 'Træning slut for i dag', 'Which trick?': 'Hvilket trick?', 'Not now': 'Ikke nu',
    'Give a treat when he looks at you.': 'Giv en godbid, når han kigger på dig.', 'Treat': 'Godbid',
    'High five': 'High five', 'Roll over': 'Rul rundt', 'Fetch the feather': 'Hent fjeren', 'Up the tower': 'Op i tårnet',
    'Dexter learnt a new trick! Tap him at home to see it.': 'Dexter har lært et nyt trick! Tryk på ham derhjemme for at se det.',
    'A good lesson. Again tomorrow.': 'En god lektion. Igen i morgen.',
    'Dexter was more interested in the treats. Again tomorrow.': 'Dexter var mest interesseret i godbidderne. Igen i morgen.',
    'A tulip of every colour': 'En tulipan i hver farve', 'See every colour of tulip bloom in your garden.': 'Se alle farver tulipaner blomstre i din have.',
    'Pink': 'Lyserød', 'Yellow': 'Gul', 'Purple': 'Lilla', 'Orange': 'Orange', 'Arrange': 'Indret', 'Arrange the shop': 'Indret butikken', 'Drag the furniture where you like it': 'Træk møblerne hen, hvor du vil have dem', 'Usual spots': 'Som før', 'Done': 'Færdig',
    'A customer is already at the door.': 'Der står allerede en kunde ved døren.', '{0} customers are already at the door.': 'Der står allerede {0} kunder ved døren.', 'There is a letter in the post.': 'Der ligger et brev i posten.', 'Badminton with Adam': 'Badminton med Adam',
    'Beach day at Amager Strand': 'Stranddag på Amager Strand', 'Movie night with popcorn': 'Filmaften med popcorn', 'Ice cream in Nyhavn': 'Is i Nyhavn',
    'Copenhagen Zoo': 'Zoologisk Have', 'Date night with Adam': 'Kæresteaften med Adam', 'Family day at Tivoli': 'Familiedag i Tivoli',
    'Elizabeth drew a dress for the shop window. It has seven sleeves.': 'Elizabeth tegnede en kjole til butiksvinduet. Den har syv ærmer.',
    'Dexter knocked a spool of thread off the table. Then another. Then another.': 'Dexter skubbede en trådrulle ned fra bordet. Og så en til. Og så en til.',
    'Adam made æbleskiver for everyone.': 'Adam lavede æbleskiver til hele familien.',
    'Elizabeth asked why the sky is blue. Then why fabric is blue. Then why Dexter is grey.': 'Elizabeth spurgte, hvorfor himlen er blå. Så hvorfor stof er blåt. Så hvorfor Dexter er grå.',
    'Dexter fell asleep on the pattern paper. Nobody dared to move him.': 'Dexter faldt i søvn på mønsterpapiret. Ingen turde flytte ham.',
    'Adam read "Rasmus Klump" three times in a row at bedtime.': 'Adam læste "Rasmus Klump" tre gange i træk ved sengetid.',
    'Elizabeth "helped" pin a hem. Mie found pins in the teddy bear.': 'Elizabeth "hjalp" med at nåle en søm op. Mie fandt knappenåle i bamsen.',
    'Dexter brought Mie a button. Probably from the shop. Probably expensive.': 'Dexter kom med en knap til Mie. Nok fra butikken. Nok dyr.',
    'The whole family had hygge with candles and cocoa.': 'Hele familien hyggede med stearinlys og kakao.',
    "Elizabeth wore Mie's tape measure as a necklace all evening.": 'Elizabeth gik med Mies målebånd som halskæde hele aftenen.',
    'Small flat in Nørrebro': 'Lille lejlighed på Nørrebro', 'Apartment on Frederiksberg': 'Ejerlejlighed på Frederiksberg', 'Rækkehus in Valby': 'Rækkehus i Valby',
    'Parcelhus in Lyngby': 'Parcelhus i Lyngby', 'Villa in Hellerup': 'Villa i Hellerup', 'Strandvejsvilla in Klampenborg': 'Strandvejsvilla i Klampenborg',
    'A rented two-room flat on the {0}th floor, no lift. Cosy, says Mie. Small, says Adam.': 'En lejet toværelses på {0}. sal uden elevator. Hyggelig, siger Mie. Lille, siger Adam.',
    'A room of her own for Elizabeth, and a balcony for Dexter to judge the birds from.': 'Et værelse til Elizabeth og en altan, hvorfra Dexter kan bedømme fuglene.',
    'A terraced house with a little garden and a door straight out.': 'Et rækkehus med en lille have og en dør lige ud.',
    'A proper house with a big garden, a swing and an apple tree.': 'Et rigtigt hus med stor have, gynge og et æbletræ.',
    'Bay windows, herringbone floors and a wine cellar for Adam.': 'Karnapvinduer, sildebensparket og en vinkælder til Adam.',
    'The dream: a white villa on Strandvejen with a view over Øresund.': 'Drømmen: en hvid villa på Strandvejen med udsigt over Øresund.',

    // ---------- wardrobe ----------
    'Teal work top': 'Petrol arbejdsbluse', 'Comfy, practical, covered in threads.': 'Behagelig, praktisk og fuld af tråde.',
    'Breton stripes': 'Bretonske striber', 'Very French. Very chic.': 'Meget fransk. Meget chik.',
    'Chunky knit sweater': 'Tyk strikket sweater', 'Hygge you can wear. Extra charming in winter.': 'Hygge, man kan have på. Ekstra charmerende om vinteren.',
    'Linen summer dress': 'Sommerkjole i hør', 'Light and breezy. Extra charming in summer.': 'Let og luftig. Ekstra charmerende om sommeren.',
    'Silk blouse with bow': 'Silkebluse med sløjfe', 'Soft pink silk, sewn by Mie herself.': 'Blød rosa silke, syet af Mie selv.',
    'Trench coat': 'Trenchcoat', 'For Copenhagen drizzle. Extra charming in autumn.': 'Til københavnsk støvregn. Ekstra charmerende om efteråret.',
    'Tailored blazer': 'Skræddersyet blazer', 'Means business. Bankers suddenly take her calls.': 'Ser forretningsmæssig ud. Bankfolk tager pludselig telefonen.',
    'Velvet evening gown': 'Aftenkjole i fløjl', 'For gala nights. Customers ask who made it.': 'Til gallaaftener. Kunderne spørger, hvem der har syet den.',
    'Tape measure': 'Målebånd', 'Never leaves home without it.': 'Går aldrig hjemmefra uden det.',
    'No accessory': 'Intet tilbehør', 'Simple and clean.': 'Enkelt og rent.',
    'Flower hair clip': 'Hårspænde med blomst', 'A little spring in her hair. Extra charming in spring.': 'Lidt forår i håret. Ekstra charmerende om foråret.',
    'Silk scarf': 'Silketørklæde', 'Tied the Parisian way.': 'Bundet på pariservis.',
    'Red beret': 'Rød baret', 'Artistic and a little bit cheeky.': 'Kunstnerisk og lidt fræk.',
    'Pearl necklace': 'Perlekæde', 'A classic. Grandma would approve.': 'En klassiker. Mormor ville nikke anerkendende.',
    'Round, dark brown': 'Runde, mørkebrune', 'Her trusty round glasses.': 'Hendes trofaste runde briller.',
    'Round, tortoiseshell': 'Runde, skildpadde', 'Warm and bookish.': 'Varme og boglærde.',
    'Round, cherry red': 'Runde, kirsebærrøde', 'A pop of colour.': 'Et pift af farve.',
    'Round, thin gold': 'Runde, tynde guld', 'Light and elegant.': 'Lette og elegante.',

    // ---------- goals ----------
    'First stitch': 'Første sting', 'Deliver your first dress.': 'Aflevér din første kjole.',
    'Word of mouth': 'Mund til mund', 'Deliver {0} dresses that score {1}% or more.': 'Aflevér {0} kjoler, der får {1}% eller mere.',
    'Built to last': 'Bygget til at holde', 'Make {0} dresses for hands-on workers.': 'Sy {0} kjoler til praktikere.',
    'Familiar faces': 'Kendte ansigter', 'Have {0} regular customers at the same time.': 'Hav {0} stamkunder på samme tid.',
    'Masterpiece': 'Mesterværk', 'Deliver a dress that scores {0}% or more.': 'Aflevér en kjole, der får {0}% eller mere.',
    'Off the rack': 'Fra stativet', 'Sell {0} ready-to-wear dresses.': 'Sælg {0} kjoler fra stativet.',
    'Muddy hands': 'Ler på hænderne', 'Sell {0} pieces of pottery.': 'Sælg {0} stykker keramik.',
    'Cosy corner': 'Hyggekrog', 'Reach {0} shop charm.': 'Nå {0} i butikscharme.',
    'Talk of the town': 'Byens samtaleemne', 'Reach reputation {0}.': 'Nå et omdømme på {0}.',
    'Tea time': 'Tetid', 'Fire a teapot in the kiln without it cracking.': 'Brænd en tekande i ovnen, uden at den revner.',
    'All year round': 'Hele året rundt', 'Deliver a dress in all four seasons.': 'Aflevér en kjole i alle fire årstider.',
    'Nest egg': 'Opsparing', 'Have {0} kr in the bank.': 'Hav {0} kr i banken.',
    'Moving on up': 'Op i verden', 'Open the upstairs floor.': 'Åbn 1. sal.',
    'Copenhagen icon': 'Københavnerikon',
    'One month in': 'En måned gået', 'Keep the atelier open for {0} days.': 'Hold atelieret åbent i {0} dage.',
    'Happy home': 'Lykkeligt hjem', 'Get family happiness to {0}.': 'Få familiens glæde op på {0}.',
    'Potter and painter': 'Keramiker og maler', 'Fire a hand-painted pot.': 'Brænd en håndmalet potte.',
    'Room to grow': 'Plads til at vokse', 'Move out of the small flat in Nørrebro.': 'Flyt ud af den lille lejlighed på Nørrebro.',
    'Strandvejsvilla!': 'Strandvejsvilla!', 'Move into the villa on Strandvejen.': 'Flyt ind i villaen på Strandvejen.',
    'Style icon': 'Stilikon', 'Wear an outfit worth {0} style charm.': 'Bær et sæt tøj med {0} stilcharme.',
    'Say yes to the dress': 'Sig ja til kjolen', "Make a bride's dress that scores {0}% or more.": 'Sy en brudekjole, der får {0}% eller mere.',

    // ---------- decor, staff, marketing ----------
    'Monstera plant': 'Monstera', 'A big green friend by the door.': 'En stor grøn ven ved døren.',
    'Window flowers': 'Blomster i vinduet', 'Tulips under the shop window.': 'Tulipaner under butiksvinduet.',
    'Persian rug': 'Persisk tæppe', 'Soft underfoot, lovely to look at.': 'Blødt under fødderne, dejligt at se på.',
    'Gilded mirror': 'Forgyldt spejl', 'Customers love seeing themselves in your work.': 'Kunderne elsker at se sig selv i dit arbejde.',
    'Sketch gallery': 'Skitsegalleri', "Framed sketches of Mie's best designs.": 'Indrammede skitser af Mies bedste designs.',
    'Espresso machine': 'Espressomaskine', 'A cup of coffee makes every fitting nicer.': 'En kop kaffe gør enhver prøvning hyggeligere.',
    'Velvet armchair': 'Lænestol i fløjl', 'Somewhere for husbands and friends to wait.': 'Et sted, hvor ægtemænd og veninder kan vente.',
    'Neon sign': 'Neonskilt', "A glowing pink “Mie's” above the door.": 'Et lysende lyserødt “Mie\'s” over døren.',
    'Crystal chandelier': 'Krystallysekrone', 'Pure sparkle. The gala crowd notices.': 'Ren glans. Gallapublikummet lægger mærke til det.',
    'Candy stripes': 'Slikstriber', 'Botanical': 'Botanisk', 'Damask': 'Damask', 'Midnight gold': 'Midnatsguld',
    'Oskar, apprentice': 'Oskar, lærling', 'Lise, shop assistant': 'Lise, butiksassistent',
    'Cuts patterns so carefully that every dress uses {0}% less fabric, and steadies the fabric so the stitch zone is wider.': 'Klipper mønstre så omhyggeligt, at hver kjole bruger {0}% mindre stof, og holder stoffet stille, så stingzonen bliver bredere.',
    'Room for one more customer each day. Customers you could not help leave with a voucher, so no reputation is lost.': 'Plads til én kunde mere hver dag. Kunder, du ikke nåede, går med et gavekort, så du mister ikke omdømme.',
    'Flyers on Strøget': 'Flyers på Strøget', '+{0} customer tomorrow.': '+{0} kunde i morgen.',
    'Ad in the local paper': 'Annonce i lokalavisen', '+{0} customer and {1}% bigger budgets tomorrow.': '+{0} kunde og {1}% større budgetter i morgen.',
    'Influencer shout-out': 'Shout-out fra en influencer', "Tomorrow's first customer is one of the fanciest types you have unlocked.": 'Morgendagens første kunde er en af de fineste typer, du har låst op for.',
    'Host a fashion show': 'Hold et modeshow', '+{0} reputation right away and +{1} customers tomorrow.': '+{0} omdømme med det samme og +{1} kunder i morgen.',

    // ---------- requirements ----------
    'It needs pockets!': 'Den skal have lommer!',
    'Long sleeves': 'Lange ærmer', 'Long sleeves, please. I get cold.': 'Lange ærmer, tak. Jeg fryser let.',
    'Short or no sleeves': 'Korte eller ingen ærmer', 'Short sleeves or none. It will be hot!': 'Korte ærmer eller ingen. Det bliver varmt!',
    'Knee length or longer': 'Knælang eller længere', 'Nothing shorter than the knee.': 'Intet, der er kortere end knæet.',
    'Not floor length': 'Ikke gulvlang', 'Not floor length. I bike everywhere.': 'Ikke gulvlang. Jeg cykler overalt.',
    'Floor length': 'Gulvlang', 'It must be floor length.': 'Den skal være gulvlang.',
    'No sequins': 'Ingen pailletter', "No sequins, please. It's an office, not a disco.": 'Ingen pailletter, tak. Det er et kontor, ikke et diskotek.',
    'Not white or ivory': 'Ikke hvid eller elfenben', "And of course it can't be white or ivory!": 'Og selvfølgelig må den ikke være hvid eller elfenben!',
    'No polyester': 'Ingen polyester', 'Absolutely no polyester.': 'Absolut ingen polyester.',

    // ---------- customer types, lines, jobs ----------
    'Hands-on worker': 'Praktiker', 'Student on a budget': 'Studerende med stramt budget', 'Summer picnic': 'Sommerpicnic', 'Office professional': 'Kontorprofessionel',
    'Cozy winter': 'Hyggelig vinter', 'Free-spirited artist': 'Fri kunstnersjæl', 'Wedding guest': 'Bryllupsgæst', 'Influencer': 'Influencer', 'Gala night': 'Gallaaften', 'Bride-to-be': 'Kommende brud',
    'I need a dress I can actually work in.': 'Jeg har brug for en kjole, jeg rent faktisk kan arbejde i.',
    'My last dress fell apart in a week. Never again!': 'Min sidste kjole faldt fra hinanden på en uge. Aldrig igen!',
    'Something fun for campus, and cheap-ish please!': 'Noget sjovt til campus, og helst billigt!',
    'Exams are over. I deserve a new dress!': 'Eksamen er overstået. Jeg fortjener en ny kjole!',
    "We're having a picnic at Dyrehavsbakken this weekend!": 'Vi skal på picnic på Dyrehavsbakken i weekenden!',
    'Summer is finally here and my wardrobe is not ready.': 'Sommeren er endelig her, og min garderobe er ikke klar.',
    'I have a big board meeting coming up.': 'Jeg har et stort bestyrelsesmøde snart.',
    'I need something sharp for the office.': 'Jeg har brug for noget skarpt til kontoret.',
    'Winter in Denmark is long and grey...': 'Vinteren i Danmark er lang og grå...',
    'I want to be warm AND look nice for once.': 'Jeg vil for en gangs skyld være varm OG se godt ud.',
    'My exhibition opens next week.': 'Min udstilling åbner i næste uge.',
    'I want a dress that is a piece of art in itself.': 'Jeg vil have en kjole, der er et kunstværk i sig selv.',
    'My best friend is getting married!': 'Min bedste veninde skal giftes!',
    "I'm invited to a wedding at a castle in Jutland.": 'Jeg er inviteret til bryllup på et slot i Jylland.',
    'I have {0}k followers and they need content.': 'Jeg har {0}k følgere, og de skal have indhold.',
    'Nobody, and I mean NOBODY, can have this dress.': 'Ingen, og jeg mener INGEN, må have denne kjole.',
    'The Royal Theatre gala is next month.': 'Gallaen på Det Kongelige Teater er i næste måned.',
    'There will be photographers. Many photographers.': 'Der kommer fotografer. Mange fotografer.',
    "I'm getting married!! And I want YOU to make my dress.": 'Jeg skal giftes!! Og jeg vil have, at DU syr min kjole.',
    "It's the most important dress of my life. No pressure! 😅": 'Det er mit livs vigtigste kjole. Intet pres! 😅',
    'gardener': 'gartner', 'veterinarian': 'dyrlæge', 'chef': 'kok', 'carpenter': 'tømrer', 'florist': 'blomsterbinder', 'farmer': 'landmand', 'potter': 'keramiker',
    'student': 'studerende', 'teacher': 'lærer', 'nurse': 'sygeplejerske', 'librarian': 'bibliotekar', 'baker': 'bager', 'dentist': 'tandlæge',
    'lawyer': 'advokat', 'accountant': 'revisor', 'actuary': 'aktuar', 'architect': 'arkitekt', 'banker': 'bankrådgiver', 'project manager': 'projektleder',
    'postwoman': 'postbud', 'pharmacist': 'farmaceut', 'museum guide': 'museumsguide', 'painter': 'maler', 'musician': 'musiker', 'sculptor': 'billedhugger',
    'poet': 'digter', 'tattoo artist': 'tatovør', 'engineer': 'ingeniør', 'journalist': 'journalist', 'influencer': 'influencer', 'pop singer': 'popsanger',
    'TV host': 'tv-vært', 'CEO': 'direktør', 'diplomat': 'diplomat', 'opera singer': 'operasanger', 'surgeon': 'kirurg', 'countess': 'komtesse', 'bride': 'brud',

    // ---------- customer reactions ----------
    'This is NOT what I asked for!': 'Det er IKKE det, jeg bad om!', "I can't wear this anywhere. Ever.": 'Den kan jeg ikke gå med nogen steder. Nogensinde.',
    'Are you sure you heard me right?': 'Er du sikker på, at du hørte mig rigtigt?', "I'll pay, but I'm not thrilled.": 'Jeg betaler, men jeg er ikke begejstret.',
    'This is not really what I asked for.': 'Det er ikke rigtig det, jeg bad om.', 'Well... I suppose I can wear it at home.': 'Nå... jeg kan vel gå med den derhjemme.',
    "It's... nice. Not quite what I pictured, but nice.": 'Den er... fin. Ikke helt som jeg forestillede mig, men fin.',
    'Hmm, okay. It will do.': 'Hmm, okay. Den går an.', "It's fine. Just fine.": 'Den er fin. Bare fin.',
    'I love it! Thank you so much.': 'Jeg elsker den! Tusind tak.', 'Oh, this is lovely. Great work!': 'Åh, den er dejlig. Flot arbejde!',
    "Wonderful. I'll tell all my friends.": 'Vidunderligt. Det fortæller jeg alle mine veninder.',
    "I'm speechless. This is the most beautiful thing I've ever owned!": 'Jeg er målløs. Det er det smukkeste, jeg nogensinde har ejet!',
    'Mie, you are a genius!': 'Mie, du er et geni!', "I'm going to wear this until it falls apart. Which will be never.": 'Jeg vil gå med den, til den falder fra hinanden. Hvilket bliver aldrig.',
    'Mie! Your last dress was a hit. Everyone asked where I got it!': 'Mie! Din sidste kjole var et hit. Alle spurgte, hvor jeg havde den fra!',
    "Hi again! I'm back for another one.": 'Hej igen! Jeg er tilbage efter en til.',
    "I'm giving you another chance. Let's do better this time, okay?": 'Jeg giver dig en chance til. Lad os gøre det bedre denne gang, okay?',
    'Some of the seams look a little wobbly.': 'Nogle af sømmene ser lidt vaklende ud.',

    // ---------- top bar & navigation ----------
    'Day': 'Dag', 'Season': 'Sæson', 'Bank': 'Bank', 'Reputation': 'Omdømme',
    'Shop': 'Butik', 'Market': 'Marked', 'Workshop': 'Værksted', 'Pottery': 'Keramik', 'Home': 'Hjem', 'Upgrades': 'Opgradér', 'Goals': 'Mål', 'Menu': 'Menu',
    "Mie's shop": 'Mies butik', "Mie's home": 'Mies hjem', 'Dress preview': 'Forhåndsvisning af kjole',

    // ---------- welcome & intro ----------
    'Welcome! You play as Mie, a dressmaker with her own little shop in Copenhagen. Keep the name or type your own. Each player gets their own shop, saved on this device.': 'Velkommen! Du spiller som Mie, en dameskrædder med sin egen lille butik i København. Behold navnet, eller skriv dit eget. Hver spiller får sin egen butik, gemt på denne enhed.',
    'Your name': 'Dit navn', 'Start playing': 'Begynd at spille',
    'Have a save code from another device? Start, then open Menu → Save → Import.': 'Har du en gemmekode fra en anden enhed? Start spillet, og åbn så Menu → Gem → Importér.',
    'Mie has just opened a tiny dress shop on a cobbled street in Copenhagen. She has a sewing machine, a dress form, {0} kr in the bank and big dreams.': 'Mie har lige åbnet en lille kjolebutik på en brostensgade i København. Hun har en symaskine, en dukke, {0} kr i banken og store drømme.',
    'Meet customers.': 'Mød kunderne.',
    'Each one has wishes: quality, workwear, creativity, exclusivity, elegance or comfort, plus favourite colours, must-haves and a budget.': 'Hver kunde har ønsker: kvalitet, arbejdstøj, kreativitet, eksklusivitet, elegance eller komfort, plus yndlingsfarver, krav og et budget.',
    'Shop the market.': 'Køb ind på markedet.',
    'Buy fabric by the metre and notions like buttons, zippers and lace. Prices change every day.': 'Køb stof i metermål og tilbehør som knapper, lynlåse og blonder. Priserne ændrer sig hver dag.',
    'Design the dress.': 'Design kjolen.',
    'Pick fabrics, colours, silhouette, length, neckline, sleeves, closure and extras. The bars show how close you are.': 'Vælg stof, farver, silhuet, længde, halsudskæring, ærmer, lukning og ekstra detaljer. Søjlerne viser, hvor tæt du er på.',
    'Sew it.': 'Sy den.', 'Tap in time with the needle. Neat stitches mean better quality.': 'Tryk i takt med nålen. Pæne sting giver bedre kvalitet.',
    'Get paid and grow.': 'Få betaling, og voks.',
    'Happy customers pay in full, tip and come back. Spend the money on upgrades and unlock fancier clients.': 'Glade kunder betaler det fulde beløb, giver drikkepenge og kommer igen. Brug pengene på opgraderinger, og lås op for finere kunder.',
    'Open the shop': 'Åbn butikken',

    // ---------- shop ----------
    "A dress for the rack is on the cutting table. Let's finish it!": 'En kjole til stativet ligger på tilskæringsbordet. Lad os gøre den færdig!',
    'One customer is waiting. Tap her to hear what she wants.': 'Én kunde venter. Tryk på hende for at høre, hvad hun vil have.',
    '{0} customers are waiting. Who should I help first?': '{0} kunder venter. Hvem skal jeg hjælpe først?',
    'Everyone has been helped. Time to close up and put the kettle on.': 'Alle har fået hjælp. Tid til at lukke og sætte kedlen over.',
    'Fashion Week buzz: customers bring {0}% bigger budgets today.': 'Fashion Week-stemning: kunderne har {0}% større budgetter med i dag.',
    'Rainy day in Copenhagen. Fewer customers are out shopping.': 'Regnvejrsdag i København. Færre kunder er ude at handle.',
    'Dresses made': 'Kjoler syet', 'Avg. satisfaction': 'Gns. tilfredshed', 'Rent tonight': 'Husleje i aften', 'Rent + wages tonight': 'Husleje + løn i aften',
    'Shop charm': 'Butikscharme', 'Regulars': 'Stamkunder', "Mie's mood": 'Mies humør',
    'Close shop for today': 'Luk butikken for i dag', 'Tap again: {0} will leave (−rep)': 'Tryk igen: {0} går (−omdømme)',
    'Current order': 'Aktuel ordre', 'Go to the workshop': 'Gå til værkstedet', 'Waiting in the shop': 'Venter i butikken', 'Nobody waiting': 'Ingen venter',
    'Finish the current order, then close the shop for the day.': 'Gør den aktuelle ordre færdig, og luk så butikken for i dag.',
    'All customers have been served. Close the shop to start a new day.': 'Alle kunder er betjent. Luk butikken for at starte en ny dag.',
    'Regular': 'Stamkunde', 'Ready-to-wear rack': 'Stativ med færdigsyede kjoler', 'Ready-to-wear dress': 'Færdigsyet kjole',
    'For the rack. Walk-in shoppers buy in the evening.': 'Til stativet. Forbipasserende køber om aftenen.',
    '{0} of {1} hangers · each dress has a {2}% chance to sell every evening': '{0} af {1} bøjler · hver kjole har {2}% chance for at blive solgt hver aften',
    'Mark down {0}%': 'Sæt ned med {0}%',
    'Nothing on the rack yet. Sew a dress without an order to use up leftover fabric and earn money while you sleep.': 'Der hænger intet på stativet endnu. Sy en kjole uden ordre for at bruge stofrester og tjene penge, mens du sover.',
    'Sew a dress for the rack': 'Sy en kjole til stativet', 'Sew for the rack': 'Sy til stativet', 'Finish the current order first.': 'Gør den aktuelle ordre færdig først.',

    // ---------- request ----------
    'Wishes': 'Ønsker', 'Must have': 'Krav', 'Colours': 'Farver', 'loves': 'elsker', 'dislikes': 'kan ikke lide', 'Fancies': 'Kan lide', 'Budget': 'Budget',
    'Decline (−{0} rep)': 'Afslå (−{0} omdømme)', 'Not yet': 'Ikke endnu', 'Accept order': 'Tag ordren', 'Back to work': 'Tilbage til arbejdet',
    'Finish your current order before taking a new one.': 'Gør din aktuelle ordre færdig, før du tager en ny.',

    // ---------- market ----------
    'Fabric stalls': 'Stofboder', 'Price per metre today. Prices move every morning.': 'Pris pr. meter i dag. Priserne ændrer sig hver morgen.',
    'Price per metre today · haggling −{0}%. Prices move every morning.': 'Pris pr. meter i dag · prutning −{0}%. Priserne ændrer sig hver morgen.',
    'in season +{0}%': 'i sæson +{0}%', 'off-season −{0}%': 'uden for sæson −{0}%', 'in season': 'i sæson', 'off-season': 'uden for sæson',
    'Own {0} m': 'Har {0} m', 'Own {0}': 'Har {0}', 'Own {0} kg': 'Har {0} kg', 'Own {0} · one per pot': 'Har {0} · én pr. potte', 'Own {0} · for gold rims': 'Har {0} · til guldkanter',
    'Supplier network level {0}': 'Leverandørnetværk niveau {0}', 'Embroidery machine level {0}': 'Broderimaskine niveau {0}', 'Reputation {0}': 'Omdømme {0}',
    'Notions': 'Tilbehør', 'Each dress uses one of each notion you add.': 'Hver kjole bruger én af hvert stykke tilbehør, du tilføjer.',
    'Clay and glazes': 'Ler og glasurer', 'For the pottery studio.': 'Til keramikværkstedet.',
    'Open the pottery studio (Upgrades → Expansion) to start throwing pots.': 'Åbn keramikværkstedet (Opgraderinger → Udvidelse) for at begynde at dreje potter.',
    'SALE −{0}%': 'UDSALG −{0}%',

    // ---------- workshop ----------
    'Fabric': 'Stof', 'Shape': 'Form', 'Details': 'Detaljer', 'Extras': 'Ekstra', 'Read request': 'Læs ønsket',
    'Main fabric': 'Hovedstof', 'Main colour': 'Hovedfarve', 'Accent fabric': 'Kontraststof', 'Accent colour': 'Kontrastfarve', 'Accent': 'Kontrast',
    'used for sleeves, collar, pockets and ruffles': 'bruges til ærmer, krave, lommer og flæser', 'No accent': 'Ingen kontrast', 'use main fabric': 'brug hovedstoffet',
    'Silhouette': 'Silhuet', 'Length': 'Længde', 'Neckline': 'Halsudskæring', 'Sleeves': 'Ærmer', 'Closure': 'Lukning',
    'a wrap dress ties itself shut, so a closure is optional': 'en slå-om-kjole bindes, så lukning er valgfri', 'every dress except a wrap needs one': 'alle kjoler undtagen slå-om skal have en',
    'more than three decorations makes a dress look over-done': 'mere end tre udsmykninger får en kjole til at se overlæsset ud',
    '{0} m fabric': '{0} m stof', 'free': 'gratis', 'own {0}': 'har {0}', 'locked': 'låst', 'needs embroidery machine': 'kræver broderimaskine',
    'Dress for the rack': 'Kjole til stativet', 'No customer: walk-in shoppers pay for a dress whose three best stats are high.': 'Ingen kunde: forbipasserende betaler for en kjole, hvis tre bedste egenskaber er høje.',
    'Cancel': 'Annullér', 'Careful stitching raises quality, and with it the price tag.': 'Omhyggelige sting hæver kvaliteten og dermed prisen.',
    'Materials': 'Materialer', "at today's prices": 'til dagens priser', 'over budget': 'over budget', '{0} kr margin': '{0} kr i avance',
    'Est. price tag': 'Anslået pris', 'with good stitching': 'med pæne sting', 'Est. price': 'Anslået pris', 'with a steady hand': 'med en sikker hånd',
    'Everything is ready on the cutting table.': 'Alt er klar på tilskæringsbordet.',
    'This dress needs a closure: a zipper or buttons.': 'Denne kjole skal have en lukning: lynlås eller knapper.',
    'The accent fabric is only used for sleeves, collar, pockets and ruffles.': 'Kontraststoffet bruges kun til ærmer, krave, lommer og flæser.',
    'Over-decorated: −{0} elegance': 'Overlæsset: −{0} elegance',
    "Buy what's missing ({0} kr)": 'Køb det, der mangler ({0} kr)', 'Start sewing': 'Begynd at sy',
    'No order on the table': 'Ingen ordre på bordet',
    "Accept a customer's order in the shop, or sew a dress for the ready-to-wear rack.": 'Tag imod en kundes ordre i butikken, eller sy en kjole til stativet.',
    'Back to the shop': 'Tilbage til butikken',

    // ---------- sewing & mini-games ----------
    'Sewing a dress for the rack': 'Syr en kjole til stativet', 'Cut': 'Klip', 'Stitch': 'Sy', 'Iron': 'Stryg', 'Knead': 'Ælt', 'Wheel': 'Drejeskive', 'Paint': 'Mal',
    'Tap': 'Tryk på', 'when the needle is over the green. The gold centre is a perfect stitch.': 'når nålen er over det grønne. Den gyldne midte er et perfekt sting.',
    'Five stitches. Steady hands!': 'Fem sting. Rolige hænder!', 'Stitch!': 'Sy!', 'Perfect!': 'Perfekt!', 'Nice stitch': 'Pænt sting', 'A bit wobbly': 'Lidt vaklende', 'Oops!': 'Ups!',
    'Cut the pattern': 'Klip mønsteret ud', 'Cut the skirt panel': 'Klip skørtedelen ud', 'Cut the bodice': 'Klip overdelen ud', 'Cut a sleeve': 'Klip et ærme ud', 'Trace the dashed line with your finger, all the way round. Start at the gold dot.': 'Følg den stiplede linje med fingeren hele vejen rundt. Start ved den gyldne prik.',
    'Ready, steady, snip!': 'Klar, parat, klip!', 'Clean cut!': 'Rent snit!', 'Not bad at all.': 'Slet ikke dårligt.', 'A bit jagged...': 'Lidt takket...',
    'Iron the dress': 'Stryg kjolen', 'Hold and swipe the iron over every wrinkle before time runs out.': 'Hold og stryg strygejernet hen over hver fold, før tiden løber ud.',
    '{0} wrinkles to go': '{0} folder tilbage', 'All smooth!': 'Helt glat!', 'Crisp as a fresh baguette!': 'Sprød som en frisk baguette!', 'Nicely pressed.': 'Pænt presset.', 'Still a little crumpled...': 'Stadig lidt krøllet...',
    'Knead the clay': 'Ælt leret', 'Tap as fast as you can to push the air bubbles out. {0} kneads is perfect.': 'Tryk så hurtigt du kan for at presse luftboblerne ud. {0} æltninger er perfekt.',
    'Knead!': 'Ælt!', 'Perfectly wedged!': 'Perfekt æltet!', 'Good enough.': 'Godt nok.', 'There may be a bubble or two...': 'Der er måske en boble eller to...',
    'Paint your pot': 'Mal din potte', 'Draw on the pot with your finger. More colours and more paint make it worth more.': 'Tegn på potten med fingeren. Flere farver og mere maling gør den mere værd.',
    'Fine': 'Fin', 'Medium': 'Mellem', 'Thick': 'Tyk', '↶ Undo': '↶ Fortryd', 'Clear': 'Ryd', 'Done painting': 'Færdig med at male', 'Painting value ×{0}': 'Malingens værdi ×{0}', 'Plain pot: value ×{0}': 'Glat potte: værdi ×{0}', 'Colour {0}': 'Farve {0}',
    'Hold': 'Hold', 'the button to press on the clay, let go to ease off. Keep the marker inside the green band until the pot is done.': 'knappen nede for at presse på leret, og slip for at lette. Hold markøren inde i det grønne bånd, til potten er færdig.',
    'Centre the clay...': 'Centrér leret...', 'Nicely centred': 'Pænt centreret', 'Press harder!': 'Pres hårdere!', 'Too much pressure!': 'For meget pres!', 'Hold to press': 'Hold for at presse',
    'Beautifully centred!': 'Smukt centreret!', 'A nice, even pot.': 'En pæn, jævn potte.', 'A bit lopsided...': 'Lidt skæv...', 'Wobbly, but it holds together.': 'Vaklende, men den holder.',
    'Kneading {0}% · Centring {1}% · price tag {2} kr · crack risk {3}%': 'Æltning {0}% · centrering {1}% · pris {2} kr · risiko for revner {3}%',
    'Centring {0}% · price tag {1} kr · crack risk {2}%': 'Centrering {0}% · pris {1} kr · risiko for revner {2}%',
    'It goes into the kiln and is fired tonight. If it survives, it appears on the shelf tomorrow morning.': 'Den kommer i ovnen og brændes i nat. Hvis den overlever, står den på hylden i morgen tidlig.',
    'Back to the studio': 'Tilbage til værkstedet',
    'On the rack for {0} kr': 'På stativet til {0} kr', 'Stitching {0}% · appeal {1} / {2} · materials {3} kr': 'Sting {0}% · tiltrækning {1} / {2} · materialer {3} kr',
    'Walk-in shoppers browse the rack every evening. Each dress has a {0}% chance to sell per night. Charm and a better shop window raise the odds.': 'Forbipasserende kigger på stativet hver aften. Hver kjole har {0}% chance for at blive solgt pr. nat. Charme og et bedre butiksvindue øger chancen.',

    // ---------- result ----------
    'satisfaction': 'tilfredshed', 'Colour': 'Farve', 'Stitching': 'Sting', 'happy home': 'lykkeligt hjem', 'misses family': 'savner familien',
    'The books': 'Regnskabet', 'Payment': 'Betaling', 'Tip': 'Drikkepenge', 'Materials used': 'Brugte materialer', 'Profit': 'Overskud',

    // ---------- day end ----------
    'Dresses delivered': 'Afleverede kjoler', 'Income': 'Indtægter', 'Shop purchases': 'Indkøb til butikken', 'Family and private spending': 'Familie og privatforbrug',
    'Rent and upkeep': 'Husleje og drift', 'Staff wages': 'Personaleløn', "Adam's salary": 'Adams løn', 'Mortgage payment (realkreditlån)': 'Ydelse på realkreditlån', 'Rent for the flat': 'Husleje for lejligheden',
    "SKAT on the shop's profit of {0} kr": 'Skat af butikkens overskud på {0} kr', 'Saved by your accountant': 'Sparet takket være din revisor',
    'Customers who left unserved': 'Kunder, der gik uden at blive betjent', '{0} (Lise gave them vouchers)': '{0} (Lise gav dem gavekort)', '{0} (−{1} rep)': '{0} (−{1} omdømme)',
    'Bank balance': 'Saldo', 'At home:': 'Derhjemme:', 'Family happiness {0} (−{1}).': 'Familiens glæde {0} (−{1}).',
    'Dexter is hungry. Buy cat food on the Home screen!': 'Dexter er sulten. Køb kattemad under Hjem!',
    'Mie couldn\'t make rent, so her mum sent {0} kr. "Just this once, skat!" Next time the bank will close the shop.': 'Mie kunne ikke betale huslejen, så hendes mor sendte {0} kr. "Kun denne ene gang, skat!" Næste gang lukker banken butikken.',
    'Open the shop: day {0}': 'Åbn butikken: dag {0}', 'Day {0} is done': 'Dag {0} er slut',
    'Rack sales ({0} dress, included in income)': 'Salg fra stativet ({0} kjole, med i indtægterne)', 'Rack sales ({0} dresses, included in income)': 'Salg fra stativet ({0} kjoler, med i indtægterne)',
    'Pottery sold ({0}, included in income)': 'Solgt keramik ({0}, med i indtægterne)', 'Kiln: {0} fired perfectly': 'Ovnen: {0} brændt perfekt', 'Kiln: {0} fired, {1} cracked': 'Ovnen: {0} brændt, {1} revnet', '{0} kr to shelf': '{0} kr på hylden',
    'The bank has closed the atelier': 'Banken har lukket atelieret', 'Mie ran out of money on day {0} after making {1} dresses. Her best one scored {2}%.': 'Mie løb tør for penge på dag {0} efter at have syet {1} kjoler. Hendes bedste fik {2}%.', 'Start over': 'Start forfra',

    // ---------- pottery studio ----------
    'The pottery corner': 'Keramikhjørnet', 'Clay': 'Ler', 'Glaze': 'Glasur', 'Decoration': 'Udsmykning',
    'Clay is wedged and the wheel is ready.': 'Leret er æltet, og drejeskiven er klar.', 'Throw on the wheel': 'Drej på skiven',
    '{0} kg · ● difficulty': '{0} kg · ● sværhedsgrad', '{0} kg · ●● difficulty': '{0} kg · ●● sværhedsgrad', '{0} kg · ●●● difficulty': '{0} kg · ●●● sværhedsgrad',
    'raw clay': 'rå ler', 'own {0} · {1} kr': 'har {0} · {1} kr', 'value ×{0}': 'værdi ×{0}', 'value ×{0} · own {1} gold leaf': 'værdi ×{0} · har {1} bladguld', 'paint it yourself: up to ×{0}': 'mal den selv: op til ×{0}',
    'Kiln': 'Brændeovn', '{0} of {1} spaces · fired tonight when you close the shop': '{0} af {1} pladser · brændes i nat, når du lukker butikken',
    'Empty. Throw a pot to fill it.': 'Tom. Drej en potte for at fylde den.', '{0}% crack risk': '{0}% risiko for revner', 'Shelf': 'Hylde',
    '{0} of {1} · each pot has a {2}% chance to sell every evening · up to {3} pots add charm': '{0} af {1} · hver potte har {2}% chance for at blive solgt hver aften · op til {3} potter giver charme',
    'Nothing for sale yet.': 'Intet til salg endnu.', 'A pottery corner for Mie?': 'Et keramikhjørne til Mie?',
    'Throw cups, bowls, vases and teapots on the wheel, fire them overnight in the kiln and sell them from a shelf. Pots on display also add charm to the shop.': 'Drej kopper, skåle, vaser og tekander, brænd dem i ovnen om natten, og sælg dem fra en hylde. Udstillede potter giver også butikken charme.',
    'See the pottery studio upgrade': 'Se opgraderingen til keramikværksted',
    'Need a sheet of gold leaf.': 'Mangler et ark bladguld.', 'The kiln is full. Pots are fired overnight, so close the shop to empty it.': 'Ovnen er fuld. Potter brændes om natten, så luk butikken for at tømme den.',

    // ---------- upgrades screen ----------
    'Equipment': 'Udstyr', 'Expansion': 'Udvidelse', 'Decor': 'Indretning', 'Staff': 'Personale', 'Marketing': 'Markedsføring',
    'Equipment and shop': 'Udstyr og butik', 'Each upgrade level adds {0} kr to the daily rent.': 'Hvert opgraderingsniveau lægger {0} kr til den daglige husleje.',
    'Buy level {0}: {1} kr': 'Køb niveau {0}: {1} kr', 'Fully upgraded': 'Fuldt opgraderet', 'Who visits the shop': 'Hvem kommer i butikken',
    'visiting · {0} kr to {1} kr': 'kommer · {0} kr til {1} kr', 'from reputation {0} · {1} kr to {2} kr': 'fra omdømme {0} · {1} kr til {2} kr',
    'Grow the atelier': 'Udvid atelieret', 'Big steps. The upstairs floor adds {0} kr to the daily rent, the pottery studio {1} kr per level.': 'Store skridt. 1. sal lægger {0} kr til den daglige husleje, keramikværkstedet {1} kr pr. niveau.',
    'Decorate the shop': 'Indret butikken', 'Charm ✨ {0}: +{1} satisfaction and +{2}% customer budgets. Decor never costs rent.': 'Charme ✨ {0}: +{1} tilfredshed og +{2}% på kundernes budgetter. Indretning koster aldrig husleje.',
    '+{0} charm': '+{0} charme', 'In the shop': 'I butikken', 'Buy: {0} kr': 'Køb: {0} kr', 'Wallpaper': 'Tapet', 'only the wallpaper on the wall counts towards charm': 'kun tapetet på væggen tæller med i charmen',
    'on the wall · ✨ +{0}': 'på væggen · ✨ +{0}', 'owned: tap to hang · ✨ +{0}': 'ejet: tryk for at sætte op · ✨ +{0}', '{0} kr · ✨ +{1}': '{0} kr · ✨ +{1}',
    'Hire help': 'Ansæt hjælp', 'A one-off hiring fee, then wages every evening with the rent. You can let staff go at any time.': 'Et engangsbeløb for at ansætte, og derefter løn hver aften sammen med huslejen. Du kan til enhver tid sige personalet op.',
    'Wage {0} kr / day': 'Løn {0} kr / dag', 'Let go': 'Sig op', 'Tap again to let them go': 'Tryk igen for at sige op', 'Hire: {0} kr': 'Ansæt: {0} kr',
    'Campaigns are paid today and work tomorrow. Book as many as you like.': 'Kampagner betales i dag og virker i morgen. Book så mange du vil.',
    'Booked for tomorrow': 'Booket til i morgen', 'Book: {0} kr': 'Book: {0} kr',

    // ---------- goals screen ----------
    '{0} of {1} collected. Complete a goal, then tap to collect the reward.': '{0} af {1} indløst. Nå et mål, og tryk så for at hente belønningen.',
    '{0} kr collected': '{0} kr indløst', 'Collect {0} kr': 'Hent {0} kr',
    '{0} goal complete. Tap to collect your reward!': '{0} mål nået. Tryk for at hente din belønning!', '{0} goals complete. Tap to collect your reward!': '{0} mål nået. Tryk for at hente dine belønninger!',

    // ---------- home ----------
    'Family': 'Familie', "Mie's wardrobe": 'Mies garderobe',
    'Mie lives with her husband Adam, their daughter Elizabeth ({0}) and Dexter the cat. Home right now:': 'Mie bor med sin mand Adam, deres datter Elizabeth ({0}) og katten Dexter. Hjemmet lige nu:',
    '. Tap Dexter to pet him.': '. Tryk på Dexter for at ae ham.', 'Family happiness': 'Familiens glæde',
    'Happy and rested': 'Glad og udhvilet', 'Misses her family': 'Savner sin familie', 'Doing fine': 'Har det fint',
    '+{0} satisfaction on every dress, and steadier stitching.': '+{0} tilfredshed på hver kjole og sikrere sting.',
    '−{0} satisfaction on every dress. Spend some time with the family!': '−{0} tilfredshed på hver kjole. Brug lidt tid med familien!',
    'Above {0} Mie works better. Below {1} she gets distracted.': 'Over {0} arbejder Mie bedre. Under {1} bliver hun distraheret.',
    'Happiness drops by {0} every night (each toy slows it by {1}).': 'Glæden falder med {0} hver nat (hvert stykke legetøj bremser det med {1}).',
    'Happiness drops by {0} every night (each toy slows it by {1}), plus {2} while Dexter is hungry.': 'Glæden falder med {0} hver nat (hvert stykke legetøj bremser det med {1}), plus {2} så længe Dexter er sulten.',
    'Today': 'I dag', 'done today ✓ · ❤️ +{0}': 'gjort i dag ✓ · ❤️ +{0}', 'free · once a day · ❤️ +{0}': 'gratis · én gang om dagen · ❤️ +{0}',
    '{0} kr · one outing a day · ❤️ +{1}': '{0} kr · én udflugt om dagen · ❤️ +{1}', 'summer only · ❤️ +{0}': 'kun om sommeren · ❤️ +{0}', 'winter only · ❤️ +{0}': 'kun om vinteren · ❤️ +{0}',
    "Dexter's food": 'Dexters mad', '{0} days of food left': 'Mad til {0} dage', '{0} day of food left': 'Mad til {0} dag', 'Dexter is hungry! Mjav!': 'Dexter er sulten! Mjav!',
    'Buy Cat food ({0} days): {1} kr': 'Køb kattemad ({0} dage): {1} kr', 'Where we live': 'Hvor vi bor',
    'The family rents the flat for {0} kr per day. Adam\'s salary ({1} kr per day) goes into the family budget.': 'Familien lejer lejligheden for {0} kr om dagen. Adams løn ({1} kr om dagen) går til familiens budget.',
    'Mortgage left': 'Restgæld', '{0} years at {1}%': '{0} år til {1}%', 'Payment per day': 'Ydelse pr. dag', 'Equity': 'Friværdi',
    'Pay off {0} kr': 'Afdrag {0} kr', 'Pay off everything': 'Indfri hele lånet', 'The home is fully paid off. No more mortgage!': 'Hjemmet er betalt ud. Ikke mere realkreditlån!',
    'Start': 'Start', 'Step {0}': 'Trin {0}', '❤️ +{0} · happiness never below {1}': '❤️ +{0} · glæden kommer aldrig under {1}', 'Where the story begins': 'Hvor historien begynder',
    'Price {0} kr': 'Pris {0} kr', 'Rent {0} kr per day': 'Husleje {0} kr om dagen', 'Home sweet home': 'Ude godt, hjemme bedst', 'Moved on': 'Flyttet videre', 'Move here: {0} kr in cash': 'Flyt hertil: {0} kr kontant',
    'Toys for Elizabeth': 'Legetøj til Elizabeth', 'Things for Dexter': 'Ting til Dexter', '❤️ +{0} now, and a slower daily drop': '❤️ +{0} nu og et langsommere dagligt fald', 'At home': 'Derhjemme',
    'What Mie wears is the best advert for the atelier. Worn clothes add': 'Det, Mie har på, er den bedste reklame for atelieret. Tøj, hun har på, giver',
    'style charm': 'stilcharme', ": right now ✨ {0}, part of the shop's total charm of {1}.": ': lige nu ✨ {0}, som er en del af butikkens samlede charme på {1}.',
    'Charm raises satisfaction on every dress, customer budgets and rack sales. Seasonal pieces give +{0} extra in their season. Buying something new also makes Mie a little happier.': 'Charme hæver tilfredsheden på hver kjole, kundernes budgetter og salget fra stativet. Sæsontøj giver +{0} ekstra i sin sæson. Noget nyt at tage på gør også Mie lidt gladere.',
    'Outfits': 'Tøj', 'Accessories': 'Tilbehør', 'Glasses': 'Briller', '+{0} style': '+{0} stil',
    '+{0} style · +{1} in spring': '+{0} stil · +{1} om foråret', '+{0} style · +{1} in summer': '+{0} stil · +{1} om sommeren',
    '+{0} style · +{1} in autumn': '+{0} stil · +{1} om efteråret', '+{0} style · +{1} in winter': '+{0} stil · +{1} om vinteren',
    'Wearing it': 'Har den på', 'Put it on': 'Tag den på',

    // ---------- menu ----------
    'Close menu': 'Luk menu', 'Settings': 'Indstillinger', 'Players': 'Spillere', 'Save': 'Gem', 'Help': 'Hjælp',
    'Language / Sprog': 'Sprog / Language', 'Theme': 'Tema', 'Auto': 'Auto', 'Light': 'Lyst', 'Dark': 'Mørkt', 'Music': 'Musik', 'Sound effects': 'Lydeffekter',
    'Animations': 'Animationer', 'On': 'Til', 'Off': 'Fra', 'Tips': 'Tips', 'Mini-games': 'Minispil', 'Full': 'Fuld', 'Quick': 'Hurtig',
    'Full: cut, stitch and iron each dress; knead clay before the wheel. Quick: only the stitching and the wheel. Painting pots is always included.': 'Fuld: klip, sy og stryg hver kjole, og ælt leret før drejeskiven. Hurtig: kun syningen og drejeskiven. At male potter er altid med.',
    'Every player has their own shop on this device.': 'Hver spiller har sin egen butik på denne enhed.', 'Day {0} · {1} kr': 'Dag {0} · {1} kr', 'Playing': 'Spiller nu', 'Play': 'Spil', 'Delete': 'Slet',
    'Tap again to delete': 'Tryk igen for at slette', 'Rename': 'Omdøb', 'New player': 'Ny spiller', 'Create': 'Opret', 'Name': 'Navn',
    'Your game saves automatically on this device after every move. There is no account and no server, so nothing leaves the device unless you copy a save code.': 'Dit spil gemmes automatisk på denne enhed efter hvert træk. Der er ingen konto og ingen server, så intet forlader enheden, medmindre du kopierer en gemmekode.',
    'Earlier saves': 'Tidligere gemte spil', 'A copy is kept automatically on each day you play.': 'Der gemmes automatisk en kopi hver dag, du spiller.',
    'Day {0}': 'Dag {0}', 'Restore': 'Gendan', 'Tap again to restore': 'Tryk igen for at gendanne', 'Restored day {0}.': 'Dag {0} er gendannet.',
    'Your saved game could not be opened, but it is kept safe. Restore an earlier save below.': 'Dit gemte spil kunne ikke åbnes, men det er gemt sikkert. Gendan et tidligere spil herunder.',
    'That backup could not be opened.': 'Den kopi kunne ikke åbnes.',
    'Could not save on this device. Copy a save code from the menu to be safe.': 'Spillet kunne ikke gemmes på denne enhed. Kopiér en gemmekode fra menuen for en sikkerheds skyld.',
    'Save now': 'Gem nu', 'Move your game to another device': 'Flyt dit spil til en anden enhed',
    'Copy the save code, send it to yourself, and import it on the other device.': 'Kopiér gemmekoden, send den til dig selv, og importér den på den anden enhed.',
    'Show save code': 'Vis gemmekode', 'Copy save code': 'Kopiér gemmekode', 'Import a save code': 'Importér en gemmekode', 'Paste a code starting with MIE{0}:': 'Indsæt en kode, der starter med MIE{0}:',
    'Import as a new player': 'Importér som ny spiller', 'Start a new game for this player': 'Start et nyt spil for denne spiller',
    "Tap again to erase this player's shop and start over": 'Tryk igen for at slette denne spillers butik og starte forfra',
    'Show the introduction': 'Vis introduktionen', 'Replay the tips': 'Vis tipsene igen',

    // ---------- help topics ----------
    'The goal': 'Målet',
    "Run Mie's dress atelier in Copenhagen. Make customers happy, earn money, raise your reputation and grow the shop, while keeping the family upstairs happy. There is no end: aim for the Goals and a bride's dress.": 'Driv Mies kjoleatelier i København. Gør kunderne glade, tjen penge, hæv dit omdømme og udvid butikken, mens du holder familien glad. Der er ingen slutning: gå efter målene og en brudekjole.',
    'Customers and scoring': 'Kunder og point',
    "Each customer has wishes (hearts {0}–{1}) across quality, workwear, creativity, exclusivity, elegance and comfort, plus must-haves, colours and favourite silhouettes. Satisfaction = {2}% wishes + {3}% colour + {4}% silhouette + {5}% craft, −{6} per missed must-have, plus small bonuses for charm, season and Mie's mood. {7}%+ pays the full budget; {8}%+ adds a tip.": 'Hver kunde har ønsker (hjerter {0}–{1}) inden for kvalitet, arbejdstøj, kreativitet, eksklusivitet, elegance og komfort, plus krav, farver og yndlingssilhuetter. Tilfredshed = {2}% ønsker + {3}% farve + {4}% silhuet + {5}% håndværk, −{6} pr. manglende krav, plus små bonusser for charme, sæson og Mies humør. {7}%+ betaler hele budgettet; {8}%+ giver drikkepenge.',
    'Market and seasons': 'Marked og sæsoner',
    'Fabric is sold per metre and prices move every morning. In-season fabric costs {0}% more but gives +{1} satisfaction; off-season fabric is {2}% cheaper but gives −{3}. Seasons change every {4} days.': 'Stof sælges pr. meter, og priserne ændrer sig hver morgen. Stof i sæson koster {0}% mere, men giver +{1} tilfredshed; stof uden for sæson er {2}% billigere, men giver −{3}. Sæsonen skifter hver {4}. dag.',
    'Workshop and sewing': 'Værksted og syning',
    'Pick fabrics, colours, shape, details and extras. The bars show the dress and the black marks the wishes. Sewing is cut → stitch → iron (or only stitch in Quick mode). Better craft means higher quality.': 'Vælg stof, farver, form, detaljer og ekstra. Søjlerne viser kjolen, og de sorte mærker viser ønskerne. Syningen er klip → sy → stryg (eller kun sy i hurtig tilstand). Bedre håndværk giver højere kvalitet.',
    'Sew without an order to use leftover fabric. Rack dresses sell to walk-ins in the evening; charm and a bigger shop window help. You can mark them down.': 'Sy uden ordre for at bruge stofrester. Kjoler på stativet sælges til forbipasserende om aftenen; charme og et større butiksvindue hjælper. Du kan sætte prisen ned.',
    'Buy the studio under Upgrades → Expansion. Knead (fewer cracks), throw on the wheel (holding keeps the pressure in the green), optionally paint, and the kiln fires overnight. Pots sell from the shelf and add charm.': 'Køb værkstedet under Opgraderinger → Udvidelse. Ælt (færre revner), drej på skiven (hold knappen for at holde trykket i det grønne), mal hvis du vil, og ovnen brænder om natten. Potter sælges fra hylden og giver charme.',
    'Home and family': 'Hjem og familie',
    'The family starts in a small flat in Nørrebro and can move up in five steps to a Strandvejsvilla in Klampenborg; each home raises the lowest family happiness can fall to. Family happiness drops every night. Above {0} Mie works better, below {1} worse. Play with Elizabeth and pet Dexter daily, buy toys, go on outings (some only in summer or winter) and keep Dexter fed.': 'Familien starter i en lille lejlighed på Nørrebro og kan flytte op i fem trin til en strandvejsvilla i Klampenborg; hvert hjem hæver den laveste grænse for familiens glæde. Familiens glæde falder hver nat. Over {0} arbejder Mie bedre, under {1} dårligere. Leg med Elizabeth og ae Dexter hver dag, køb legetøj, tag på udflugter (nogle kun om sommeren eller vinteren), og husk Dexters mad.',
    "Home → Mie's wardrobe has outfits, accessories and round glasses for Mie. What she wears shows everywhere and adds style charm to the shop; seasonal pieces give +{0} extra in their season.": 'Hjem → Mies garderobe har tøj, tilbehør og runde briller til Mie. Det, hun har på, kan ses overalt og giver butikken stilcharme; sæsontøj giver +{0} ekstra i sin sæson.',
    'SKAT and the accountant': 'Skat og revisor',
    "Each evening SKAT is paid on the shop's profit: {0}% on the first {1} kr above a small allowance and {2}% top tax above that. Mortgage interest is deductible. An accountant (Upgrades → Equipment) finds more deductions, and at level {3} virksomhedsordningen lowers the top rate to {4}%.": 'Hver aften betales der skat af butikkens overskud: {0}% af de første {1} kr over et lille fradrag og {2}% topskat derover. Renter på realkreditlånet kan trækkes fra. En revisor (Opgraderinger → Udstyr) finder flere fradrag, og på niveau {3} sænker virksomhedsordningen topskatten til {4}%.',
    'Equipment improves work, expansions add pottery and an upstairs floor, decor adds charm, staff help every day for a wage, and marketing brings more or richer customers tomorrow.': 'Udstyr forbedrer arbejdet, udvidelser giver keramik og en 1. sal, indretning giver charme, personale hjælper hver dag mod løn, og markedsføring giver flere eller rigere kunder i morgen.',
    'Milestones with cash rewards. Collect them on the Goals screen.': 'Milepæle med pengebelønninger. Hent dem under Mål.',
    'Saving': 'Gemme',
    'The game saves automatically on this device. Menu → Save can make a save code to move your game to another device. Each player has their own shop.': 'Spillet gemmes automatisk på denne enhed. Menu → Gem kan lave en gemmekode, så du kan flytte spillet til en anden enhed. Hver spiller har sin egen butik.',

    // ---------- tips ----------
    'Welcome to the atelier!': 'Velkommen til atelieret!',
    'Mie makes dresses to order. Make customers happy, earn money and grow the shop. Customers wait here. Tap one to hear what she wants.': 'Mie syr kjoler efter mål. Gør kunderne glade, tjen penge, og udvid butikken. Kunderne venter her. Tryk på én for at høre, hvad hun vil have.',
    'Read the wishes': 'Læs ønskerne',
    'Hearts show what matters most. Missing a must-have costs {0} points. Loved colours and favourite silhouettes count too. Tap Accept order when you are ready.': 'Hjerterne viser, hvad der betyder mest. Et manglende krav koster {0} point. Yndlingsfarver og yndlingssilhuetter tæller også. Tryk på Tag ordren, når du er klar.',
    'Design the dress': 'Design kjolen',
    "Use the tabs to pick fabric, colour, shape, details and extras. The bars show the dress; the black marks are the customer's wishes. Reach them without spending the whole budget.": 'Brug fanerne til at vælge stof, farve, form, detaljer og ekstra. Søjlerne viser kjolen; de sorte mærker er kundens ønsker. Nå dem uden at bruge hele budgettet.',
    'Missing materials': 'Manglende materialer',
    "Mie doesn't have everything yet. Tap here to buy exactly what is missing at today's prices, or shop in the Market.": 'Mie har ikke det hele endnu. Tryk her for at købe præcis det, der mangler, til dagens priser, eller handl på markedet.',
    'Ready to sew': 'Klar til at sy',
    'Start sewing. You cut the pattern, stitch it and iron it in three quick mini-games. Neat work raises quality.': 'Begynd at sy. Du klipper mønsteret, syr det og stryger det i tre hurtige minispil. Pænt arbejde hæver kvaliteten.',
    'How did it go?': 'Hvordan gik det?',
    'Satisfaction sets the payment, tip and reputation. Higher reputation brings more customers and fancier ones with bigger budgets.': 'Tilfredsheden afgør betaling, drikkepenge og omdømme. Højere omdømme giver flere og finere kunder med større budgetter.',
    'End of the day': 'Dagen er slut',
    'Everyone has been helped. Close the shop: rent is paid, the night passes and a new day begins with new customers.': 'Alle har fået hjælp. Luk butikken: huslejen betales, natten går, og en ny dag begynder med nye kunder.',
    'The market': 'Markedet',
    'Fabric is sold by the metre. Prices change every morning (the arrows), and the six small bars show what each fabric is good at.': 'Stof sælges i metermål. Priserne ændrer sig hver morgen (pilene), og de seks små søjler viser, hvad hvert stof er godt til.',
    "Mie's family": 'Mies familie',
    'Upstairs live Adam, Elizabeth ({0}) and Dexter the cat. A happy family makes Mie work better, so visit them every day.': 'Ovenpå bor Adam, Elizabeth ({0}) og katten Dexter. En glad familie får Mie til at arbejde bedre, så besøg dem hver dag.',
    "Play with Elizabeth and pet Dexter every day for free. Toys and outings help too. And don't forget Dexter's cat food!": 'Leg med Elizabeth og ae Dexter hver dag, det er gratis. Legetøj og udflugter hjælper også. Og glem ikke Dexters kattemad!',
    'Grow the shop': 'Udvid butikken',
    'Spend money on equipment, expansions, decor (charm makes customers happier), staff and marketing.': 'Brug penge på udstyr, udvidelser, indretning (charme gør kunderne gladere), personale og markedsføring.',
    'Leftover fabric? Sew a dress without an order and hang it on the rack. Walk-in shoppers buy in the evening.': 'Stofrester? Sy en kjole uden ordre, og hæng den på stativet. Forbipasserende køber om aftenen.',
    'A new season': 'En ny sæson',
    'Every {0} days the season changes. It changes who visits and which fabrics are in season (+{1}) or off-season (−{2}).': 'Hver {0}. dag skifter sæsonen. Det ændrer, hvem der kommer, og hvilke stoffer der er i sæson (+{1}) eller uden for sæson (−{2}).',
    'Goal complete!': 'Mål nået!', 'You reached a goal. Collect the cash reward on the Goals screen.': 'Du har nået et mål. Hent pengebelønningen under Mål.',
    'A pottery corner?': 'Et keramikhjørne?', 'With some savings Mie could start making pottery too. Buy the pottery studio under Upgrades → Expansion.': 'Med lidt opsparing kunne Mie også begynde at lave keramik. Køb keramikværkstedet under Opgraderinger → Udvidelse.',
    'Pick shape, clay, glaze and decoration. Then knead, throw on the wheel and paint if you like. The kiln fires pots overnight.': 'Vælg form, ler, glasur og udsmykning. Ælt så, drej på skiven, og mal hvis du vil. Ovnen brænder potterne om natten.',
    'Something new to wear?': 'Noget nyt at tage på?', "Mie's wardrobe: new clothes make her the best advert for the atelier and add style charm.": 'Mies garderobe: nyt tøj gør hende til den bedste reklame for atelieret og giver stilcharme.',
    'SKAT is taking a bite': 'Skat tager en bid', 'A busy shop pays tax on good days. An accountant (Upgrades → Equipment) lowers it.': 'En travl butik betaler skat på gode dage. En revisor (Opgraderinger → Udstyr) sænker den.',
    'Time to move?': 'Tid til at flytte?', 'You can afford a bigger home. Each move makes the family happier for good.': 'Du har råd til et større hjem. Hver flytning gør familien gladere for altid.',
    'Mie misses her family': 'Mie savner sin familie', 'Family happiness is low, so Mie is distracted at work. Spend time at home.': 'Familiens glæde er lav, så Mie er distraheret på arbejdet. Brug tid derhjemme.',
    'Got it': 'Forstået', 'No more tips': 'Ikke flere tips',

    // ---------- toasts ----------
    'Saved on this device': 'Gemt på denne enhed', 'Save code copied': 'Gemmekode kopieret', 'Select the code and copy it.': 'Markér koden, og kopiér den.',
    'Type a name first.': 'Skriv et navn først.', 'Renamed': 'Omdøbt', 'Player deleted.': 'Spiller slettet.',
    'Tips are off. Turn them on again in Menu → Settings.': 'Tips er slået fra. Slå dem til igen under Menu → Indstillinger.', 'Tips will show again as you play.': 'Tipsene vises igen, mens du spiller.',
    'Bought the missing materials for {0} kr.': 'Købte de manglende materialer for {0} kr.', 'Not enough money: that costs {0} kr.': 'Ikke penge nok: det koster {0} kr.',
    'Not enough money for everything that is missing.': 'Ikke penge nok til alt det, der mangler.', 'Marked down to {0} kr.': 'Sat ned til {0} kr.',
    'Dexter approves.': 'Dexter godkender.', 'Dexter purrs like a little motor. ❤️ +{0}': 'Dexter spinder som en lille motor. ❤️ +{0}',
    'Dexter would rather have dinner. Mjav!': 'Dexter vil hellere have aftensmad. Mjav!', 'Dexter has had enough cuddles for today. He is a cat, after all.': 'Dexter har fået nok kram for i dag. Han er trods alt en kat.',
    'Goal complete! Collect your reward on the Goals screen.': 'Mål nået! Hent din belønning under Mål.', 'The mortgage is paid off!': 'Realkreditlånet er betalt ud!',
    'Paid {0} kr off the mortgage.': 'Betalte {0} kr af på realkreditlånet.', 'Finish the rack dress before closing.': 'Gør kjolen til stativet færdig, før du lukker.',
    'Save imported as a new player ✓ Rename it under Menu → Players.': 'Gemt spil importeret som ny spiller ✓ Omdøb den under Menu → Spillere.',
    'That does not look like a save code from Life of Mie. It should start with MIE{0}:': 'Det ligner ikke en gemmekode fra Mies liv. Den skal starte med MIE{0}:',
    'The save code is incomplete or damaged. Copy the whole code and try again.': 'Gemmekoden er ufuldstændig eller beskadiget. Kopiér hele koden, og prøv igen.',
    'The save code is not a valid game.': 'Gemmekoden er ikke et gyldigt spil.',
    'Dansk': 'Dansk', 'English': 'English', 'the rack': 'stativet', 'Wish: {0}': 'Ønske: {0}', 'Name': 'Navn',

    // ---- v1.8 cozy ----
    "Mie's idea": 'Mies idé', "Buy what's missing and sew ({0} kr)": 'Køb det manglende og sy ({0} kr)',
    'Mie sketched an idea. Change anything you like!': 'Mie har skitseret en idé. Ændr alt, hvad du vil!', 'How about this? Tap again for another idea.': 'Hvad med den her? Tryk igen for en ny idé.',
    'A little sketch from Mie. Make it your own!': 'En lille skitse fra Mie. Gør den til din egen!',
    "Mie can't think of anything we can afford today. Maybe visit the market?": 'Mie kan ikke komme i tanke om noget, vi har råd til i dag. Måske et smut på markedet?',
    '🏆 {0} goals collected: +{1} kr!': '🏆 {0} mål hentet: +{1} kr!', 'That has already been used.': 'Det er allerede brugt.',
    'Upstairs live Adam, Elizabeth and Dexter the cat. A happy family makes Mie work better, so visit them every day.': 'Ovenpå bor Adam, Elizabeth og katten Dexter. En glad familie får Mie til at arbejde bedre, så besøg dem hver dag.',
    'Payment': 'Betaling', 'Hugs 💗': 'Kram 💗', 'Hugs': 'Kram', 'for your own daughter': 'til din egen datter', 'Paid in hugs': 'Betalt med kram',
    'Winnie the Pooh teddy': 'Peter Plys-bamse', 'A bear of very little brain, with his own little honey pot. Elizabeth never lets go of him.': 'En bjørn med meget lidt forstand og sin egen lille honningkrukke. Elizabeth slipper ham aldrig.',
    'Haggle with the stallholder': 'Prut med sælgeren', 'Tap “Offer!” while the needle is in the green. Three offers.': 'Tryk på “Byd!”, mens nålen er i det grønne. Tre bud.',
    '“Well, what are you offering?”': '“Nå, hvad byder du?”', '“Hm. Fine, for you.”': '“Hm. Fint, for din skyld.”', '“You drive a hard bargain!”': '“Du er en hård forhandler!”', '“Ha! All right, all right.”': '“Ha! Okay, okay.”',
    '“Ha! Nice try.”': '“Ha! Godt forsøgt.”', '“That price? Never.”': '“Den pris? Aldrig.”', '“My children have to eat too, you know.”': '“Mine børn skal også have mad, ved du.”',
    'Offer!': 'Byd!', 'Haggled: −{0}% at the stalls today!': 'Prutet: −{0}% ved boderne i dag!', 'No luck today. Same prices as always.': 'Intet held i dag. Samme priser som altid.', '−{0}% today': '−{0}% i dag',
    'Collections': 'Samlinger', 'Little sets to complete at your own pace. Each finished set hangs a framed keepsake on the shop wall.': 'Små samlinger, du kan fuldende i dit eget tempo. Hver færdig samling hænger et indrammet minde op på butikkens væg.',
    'Fabric library': 'Stofbiblioteket', 'Sew a dress in every fabric.': 'Sy en kjole i hvert stof.', 'Every colour of the rainbow': 'Alle regnbuens farver', 'Sew a dress in every colour.': 'Sy en kjole i hver farve.',
    'The silhouette book': 'Silhuetbogen', 'Four stars or more in every silhouette.': 'Fire stjerner eller mere i hver silhuet.', "The potter's shelf": 'Keramikerens hylde', 'Fire every pot shape in the kiln.': 'Brænd hver krukkeform i ovnen.',
    'Four seasons of five stars': 'Fire årstider med fem stjerner', 'A five-star dress in every season.': 'En femstjernet kjole i hver årstid.',
    '{0} kr in the envelope.': '{0} kr i kuverten.', 'A keepsake for the shop wall (+{0} charm).': 'Et minde til butikkens væg (+{0} charme).', 'It made the whole family smile.': 'Det fik hele familien til at smile.',
    'In the post': 'I posten',
    'Album': 'Album', 'Stories': 'Historier', 'Lookbook': 'Lookbook', 'Letters': 'Breve', 'Life stories': 'Livshistorier',
    'Some customers come back as their lives move on: first dates, weddings, babies, big moments. Their dresses and letters are kept here.': 'Nogle kunder kommer igen, efterhånden som livet går videre: første dates, bryllupper, babyer, store øjeblikke. Deres kjoler og breve gemmes her.',
    'Next chapter': 'Næste kapitel', 'When the shop is better known': 'Når butikken er mere kendt', 'She will drop by one of these days': 'Hun kigger forbi en af dagene',
    'A chapter still to come': 'Et kapitel, der venter', 'Someone you have not met yet': 'En, du ikke har mødt endnu', 'Every life has a story. Keep the shop open.': 'Alle liv har en historie. Hold butikken åben.',
    'Every dress with four stars or more, and every dress from a life story.': 'Alle kjoler med fire stjerner eller mere, og alle kjoler fra en livshistorie.',
    'Your first four-star dress will be the first page.': 'Din første kjole med fire stjerner bliver første side.',
    'Thank-you notes and postcards from customers.': 'Takkekort og postkort fra kunder.', 'A new letter is waiting': 'Der ligger et nyt brev', '{0} new letters are waiting': 'Der ligger {0} nye breve',
    'No letters yet.': 'Ingen breve endnu.', 'A letter from': 'Et brev fra', '{0} letters in the post': '{0} breve i posten',
    'She tucked {0} kr into the envelope.': 'Hun har lagt {0} kr i kuverten.', 'She sent a little something for Elizabeth.': 'Hun har sendt en lille ting til Elizabeth.',
    'She sent a keepsake for the shop wall (+{0} charm).': 'Hun har sendt et minde til butikkens væg (+{0} charme).', 'Keep it in the album': 'Gem det i albummet',
    'A new page in her story': 'En ny side i hendes historie', 'Added to the lookbook': 'Lagt i lookbooken', 'Her story': 'Hendes historie',
    'Ambience': 'Stemning', 'Year {0}': 'År {0}', 'Purse': 'Pung', 'Reputation {0} of {1}': 'Omdømme {0} af {1}', '{0} of {1} stars': '{0} af {1} stjerner',
    'Happy customers': 'Glade kunder', 'Tap again: she pops back tomorrow': 'Tryk igen: hun kigger forbi i morgen', 'Tap again: they pop back tomorrow': 'Tryk igen: de kigger forbi i morgen',
    'Kindly decline': 'Sig venligt nej tak',
    'Over the moon': 'I den syvende himmel', 'Delighted': 'Begejstret', 'Happy': 'Glad', 'Pleased enough': 'Godt tilfreds', 'A polite smile': 'Et høfligt smil',
    'Paid {0} kr': 'Betalt {0} kr', 'Paid {0} kr and a {1} kr tip': 'Betalt {0} kr og {1} kr i drikkepenge',
    'How did she judge it?': 'Hvordan bedømte hun den?', 'Hide the details': 'Skjul detaljerne', 'Next customer:': 'Næste kunde:', 'Satisfaction': 'Tilfredshed',
    'A dress went home with its new owner.': 'En kjole kom hjem med sin nye ejer.', '{0} dresses went home with their new owners.': '{0} kjoler kom hjem med deres nye ejere.',
    'Walk-in shoppers took {0} dress from the rack.': 'Forbipasserende tog {0} kjole fra stativet.', 'Walk-in shoppers took {0} dresses from the rack.': 'Forbipasserende tog {0} kjoler fra stativet.',
    '{0} pot found a new home.': '{0} krukke fandt et nyt hjem.', '{0} pots found a new home.': '{0} krukker fandt et nyt hjem.',
    'The kiln is warm: {0} new pot for the shelf tomorrow.': 'Ovnen er varm: {0} ny krukke til hylden i morgen.', 'The kiln is warm: {0} new pots for the shelf tomorrow.': 'Ovnen er varm: {0} nye krukker til hylden i morgen.',
    '{0} pot cracked in the kiln. It happens to every potter.': '{0} krukke revnede i ovnen. Det sker for enhver keramiker.', '{0} pots cracked in the kiln. It happens to every potter.': '{0} krukker revnede i ovnen. Det sker for enhver keramiker.',
    '{0} customer will pop back tomorrow.': '{0} kunde kigger forbi igen i morgen.', '{0} customers will pop back tomorrow.': '{0} kunder kigger forbi igen i morgen.',
    "{0} customer will pop back tomorrow, after a cup of Lise's tea.": '{0} kunde kigger forbi igen i morgen, efter en kop af Lises te.', "{0} customers will pop back tomorrow, after a cup of Lise's tea.": '{0} kunder kigger forbi igen i morgen, efter en kop af Lises te.',
    'Your accountant kept {0} kr away from SKAT.': 'Din revisor holdt {0} kr væk fra SKAT.',
    'Mie\'s mum and dad popped by with an envelope: "For the shop, skat. We\'re so proud of you."': 'Mies mor og far kiggede forbi med en kuvert: "Til butikken, skat. Vi er så stolte af dig."',
    'A quiet day. The shop smells of fresh linen and tea.': 'En stille dag. Butikken dufter af frisk hør og te.',
    '{0} kr in the purse': '{0} kr i pungen', '(+{0} kr today)': '(+{0} kr i dag)', '(−{0} kr today)': '(−{0} kr i dag)',
    "Today's accounts": 'Dagens regnskab', 'Close the accounts': 'Luk regnskabet', 'Good night': 'Godnat',
    "From Mie's parents": 'Fra Mies forældre', 'Accounts': 'Regnskab',
    'Everything that came in and went out, for when you feel like doing the books.': 'Alt hvad der er kommet ind og gået ud, til når du har lyst til at gøre regnskabet op.',
    'The book is still empty. Each evening is written down here.': 'Bogen er stadig tom. Hver aften bliver skrevet ned her.',
    'The last day': 'Den seneste dag', 'The last {0} days': 'De seneste {0} dage', 'Shop takings': 'Butikkens indtægter', 'Fabric and supplies': 'Stof og materialer',
    'Family and private': 'Familie og privat', 'Shop rent and upkeep': 'Husleje og drift af butikken', 'Mortgage': 'Realkreditlån', 'Flat rent': 'Husleje for lejligheden',
    'Together': 'I alt', 'Day by day': 'Dag for dag', 'In': 'Ind', 'Out': 'Ud', 'Every day': 'Hver dag',
    'No rush, no way to lose': 'Ingen hast og ingen måde at tabe på',
    "Take your time: nothing in the shop runs on a clock. Customers you don't get to today simply pop back tomorrow, declining an order is fine, and if money ever runs low, Mie's mum and dad help out. All the money details are in Home → Accounts.": 'Tag dig god tid: intet i butikken kører på tid. Kunder, du ikke når i dag, kigger bare forbi igen i morgen, det er helt fint at sige nej tak til en ordre, og hvis pengene slipper op, hjælper Mies mor og far. Alle tal om penge står under Hjem → Regnskab.',
    'Room for one more customer each day, and she makes tea for anyone who has to come back tomorrow, so they return in a sunny mood (+{0} satisfaction).': 'Plads til én kunde mere hver dag, og hun laver te til dem, der må komme igen i morgen, så de vender tilbage i godt humør (+{0} tilfredshed).',
    'A seam or two has a little personality.': 'En søm eller to har lidt personlighed.',
  };

  // Sentences with names or other words inside. $1, $2 … are translated too when possible.
  const P = [
    [/^([\d.,]+) m (.+) for the shelf\.$/, '$1 m $2 til hylden.'], [/^(\d+) × (.+)\.$/, '$1 × $2.'],
    [/^Collection complete: (.+)! A framed keepsake goes up on the shop wall\.$/, 'Samlingen er fuldendt: $1! Et indrammet minde kommer op på butikkens væg.'],
    [/^(.+) · (\d+) of (\d+) chapters$/, '$1 · $2 af $3 kapitler'], [/^📖 Chapter (\d+): (.+)$/, '📖 Kapitel $1: $2'], [/^· (.+)$/, '· $1'],
    [/^She sent (\d+) m of (.+) she didn't need\.$/, 'Hun har sendt $1 m $2, som hun ikke skulle bruge.'],
    [/^↶ Undo: (\d+) m (.+)$/, '↶ Fortryd: $1 m $2'], [/^↶ Undo: (\d+)× (.+)$/, '↶ Fortryd: $1× $2'], [/^Returned (.+)\.$/, '$1 er leveret tilbage.'],
    [/^Evening, (spring|summer|autumn|winter) (\d+)$/, 'Aften, $1 $2'], [/^Good morning, (.+)$/, 'Godmorgen, %1'], [/^New sticker in the album: (.+)$/, 'Nyt klistermærke i albummet: $1'],
    [/^(.+) in this weather\.\.\. I'll save it for another season\.$/, '$1 i det her vejr... Den gemmer jeg til en anden sæson.'],
    [/^Next time I'd love it with: (.+)\.$/, 'Næste gang ville jeg elske den med: $1.'],
    [/^(.+) isn't really my colour, but the work is lovely\.$/, '$1 er ikke rigtig min farve, men arbejdet er smukt.'],
    [/^(.+) is going to tell all her friends about Mie's\.$/, '%1 vil fortælle alle sine veninder om Mies.'],
    [/^(.+) will be back\.$/, '%1 kommer igen.'],
    [/^(.+) might pop by again another day\.$/, '%1 kigger måske forbi en anden dag.'],
    [/^(.+) understands and wishes you a lovely day\.$/, '%1 forstår det godt og ønsker dig en dejlig dag.'],
    [/^Hi! I'm (.+), an? (.+)\.$/, 'Hej! Jeg hedder $1 og er $2.'],
    [/^It absolutely has to be (.+)\.$/, 'Den skal absolut være $1.'],
    [/^I'd love it to be (.+)\.$/, 'Jeg ville elske, hvis den var $1.'],
    [/^A little bit (.+) would be nice\.$/, 'Det ville være dejligt, hvis den også var $1.'],
    [/^I adore (.+) and (.+), but please no (.+)\.$/, 'Jeg elsker $1 og $2, men helst ikke $3.'],
    [/^I adore (.+) and (.+)\.$/, 'Jeg elsker $1 og $2.'],
    [/^My budget is (.+) kr\.$/, 'Mit budget er $1 kr.'],
    [/^I wish it was more (.+)\.$/, 'Jeg ville ønske, den var mere $1.'],
    [/^And you forgot: (.+)!$/, 'Og du glemte: $1!'],
    [/^I told you I don't like (.+)\.\.\.$/, 'Jeg sagde jo, at jeg ikke kan lide $1...'],
    [/^And the (.+)! My favourite colour!$/, 'Og så $1! Min yndlingsfarve!'],
    [/^(.+)\? In this weather\? Really\?$/, '$1? I det her vejr? Seriøst?'],
    [/^(.+) · visit no\. (\d+)$/, '$1 · besøg nr. $2'],
    [/^What (.+) judged$/, 'Hvad $1 bedømte'],
    [/^(.+) will probably come back\.$/, '$1 kommer nok igen.'],
    [/^(.+) is unlikely to come back\.$/, '$1 kommer næppe igen.'],
    [/^(.+) will never set foot in the shop again\.$/, '$1 sætter aldrig sine ben i butikken igen.'],
    [/^Sewing (.+)'s dress$/, 'Syr $1s kjole'],
    [/^(.+)'s dress won't sew itself! Off to the workshop\.$/, '$1s kjole syr ikke sig selv! Afsted til værkstedet.'],
    [/^The marks show (.+)'s wishes\. Careful stitching raises quality further\.$/, 'Mærkerne viser $1s ønsker. Omhyggelige sting hæver kvaliteten yderligere.'],
    [/^♥ = (.+) loves it, ✕ = dislikes$/, '♥ = $1 elsker den, ✕ = kan ikke lide'],
    [/^Order accepted: a dress for (.+)\.$/, 'Ordre modtaget: en kjole til $1.'],
    [/^(.+) leaves a little disappointed\.$/, '$1 går lidt skuffet.'],
    [/^Finish (.+)'s dress before closing\.$/, 'Gør $1s kjole færdig, før du lukker.'],
    [/^Welcome back, (.+)!$/, 'Velkommen tilbage, $1!'],
    [/^Rename (.+)$/, 'Omdøb $1'],
    [/^Imported \(day (\d+)\)$/, 'Importeret (dag $1)'],
    [/^Market news: (.+) is (\d+)% off today\.$/, 'Nyt fra markedet: $1 er $2% billigere i dag.'],
    [/^Today's marketing: (.+)\.$/, 'Dagens markedsføring: $1.'],
    [/^Booked for tomorrow: (.+)\.$/, 'Booket til i morgen: $1.'],
    [/^(.+) booked for tomorrow\.$/, '$1 booket til i morgen.'],
    [/^(.+) In season: (.+)\.$/, '$1 I sæson: $2.'],
    [/^(.+) is perfect for (.+): \+(\d+) satisfaction\.$/, '$1 passer perfekt til $2: +$3 tilfredshed.'],
    [/^(.+) feels wrong in (.+): −(\d+) satisfaction\.$/, '$1 føles forkert om $2: −$3 tilfredshed.'],
    [/^Need ([\d.,]+) m (.+), you have ([\d.,]+) m\.$/, 'Mangler $1 m $2, du har $3 m.'],
    [/^Need ([\d.,]+) kg (.+), you have ([\d.,]+) kg\.$/, 'Mangler $1 kg $2, du har $3 kg.'],
    [/^Need (\d+)× (.+), you have (\d+)\.$/, 'Mangler $1× $2, du har $3.'],
    [/^Need a pot of (.+) glaze\.$/, 'Mangler en krukke $1-glasur.'],
    [/^(.+) needs supplier network level (\d+)\.$/, '$1 kræver leverandørnetværk niveau $2.'],
    [/^(.+) doesn't come in that colour\.$/, '$1 findes ikke i den farve.'],
    [/^Choose a main fabric\.$/, 'Vælg et hovedstof.'],
    [/^Bought ([\d.,]+) m (.+)\.$/, 'Købte $1 m $2.'],
    [/^Bought ([\d.,]+) kg (.+)\.$/, 'Købte $1 kg $2.'],
    [/^Bought (\d+)× (.+)\.$/, 'Købte $1× $2.'],
    [/^(.+) glaze$/, '$1-glasur'],
    [/^(.+) added to the shop\. Charm is now (\d+)\.$/, '$1 er sat ind i butikken. Charmen er nu $2.'],
    [/^(.+) upgraded to level (\d+)!$/, '$1 opgraderet til niveau $2!'],
    [/^(.+) starts today!$/, '$1 starter i dag!'],
    [/^(.+) has left the atelier\.$/, '$1 har forladt atelieret.'],
    [/^(.+) for Elizabeth!$/, '$1 til Elizabeth!'],
    [/^(.+) for Dexter!$/, '$1 til Dexter!'],
    [/^(.+): family happiness \+(\d+)!$/, '$1: familiens glæde +$2!'],
    [/^The family moved to: (.+)!$/, 'Familien er flyttet til: $1!'],
    [/^Mie is wearing her new (.+)!$/, 'Mie har sin nye $1 på!'],
    [/^Mie: (.+)\.$/, 'Mie: $1.'],
    [/^Last night: (.+)$/, 'I går aftes: $1'],
    [/^(.+): \+([\d.,]+) kr!$/, '$1: +$2 kr!'],
    [/^New customers unlocked: (.+)!$/, 'Nye kunder låst op: $1!'],
    [/^Throwing a (.+)$/, 'Drejer: $1'],
    [/^Next home: (.+) for ([\d.,]+) kr\. Buying takes a (\d+)% down payment \(minus the equity in your current home\); the rest is a (\d+)-year realkreditlån at (\d+)%, about ([\d.,]+) kr per day\.$/,
      'Næste hjem: $1 til $2 kr. Købet kræver $3% i udbetaling (minus friværdien i jeres nuværende hjem); resten er et $4-årigt realkreditlån til $5%, cirka $6 kr om dagen.'],
    [/^(.+\.) Own ([\d.,]+) kg$/, '$1 Har $2 kg'],
    [/^(\d+) days left of (.+)$/, '$1 dage tilbage af $2'],
    [/^own (\d+) (.+)$/, 'har $1 $2'],
  ];
  DG.addTranslations(D, P);
})(typeof window !== 'undefined' ? window : globalThis);
